### ISSUE TITLE
total amount of AST nodes (including comments) counts for inling

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-kitchen-sink-helpers#10]
although hashTree can be inlined itself but this comment itself is nearly at the mix before it will not be allowed for inlining.

simply moving https://github.com/broccolijs/broccoli-kitchen-sink-helpers/blob/master/index.js#L10-L18 outside of the function prevents this silly issue in v8. (chakra doesn't have it..)

**Comment by joliss** [comment]
Fixed by #23.
