### ISSUE TITLE
new version of glob breaks multiGlob

### ISSUE THREAD

**Issue by ef4** [broccolijs/broccoli-kitchen-sink-helpers#27]
glob 4.3.x has breaking changes in symlink-following behavior. See https://github.com/isaacs/node-glob/issues/135. 

Given that many broccoli pipelines use extensive symlinking for performance, this is a pain.

I think we need to lock down the version constraint here to "4.0.4", at least until there's a follow-all-symlinks option in upstream glob.

**Comment by ppcano** [comment]
I confirm this issue.

**Comment by joliss** [comment]
I'll take a patch until I can investigate.

**Comment by rwjblue** [comment]
https://github.com/broccolijs/broccoli-kitchen-sink-helpers/pull/28

**Comment by isaacs** [comment]
`follow:true` option added in `glob@4.5.0`.

**Comment by joliss** [comment]
Thanks @isaacs!

I'll test and update the dependency for broccoli-kitchen-sink-helpers in 1 or 2 weeks.

**Comment by joliss** [comment]
I'll test and update the dependency for broccoli-kitchen-sink-helpers in 1 or 2 weeks, or happy to take a patch too.
